name: Partial_View
channels:
  - pytorch
  - defaults
dependencies:
  - numpy==1.23.1
  - pandas
  - matplotlib
  - pip 
  - scipy
  - sympy                        
  - tqdm
  - PyYAML
  - loguru
  - colour
  - scikit-image
  - imageio
  - python=3.8


  - pip:
    - opencv-python
    - pyrender==0.1.45
    - omegaconf
    - chumpy
    - smplx
    - transforms3d==0.3.1
    - dotmap
    - pyopengl==3.1.0
    - torch
    - pyopengl-accelerate==3.1.7
    - smplpytorch
    - moviepy
    - trimesh
